import { createSlice } from "@reduxjs/toolkit";

export const rootReducer = createSlice({
  name: "auth", // Unique name for the slice
  initialState: { isAuthenticated: false }, // Initial state for the slice
  reducers: {
    // Reducer methods
    login: (state) => {
      state.isAuthenticated = true;
    },
    logout: (state) => {
      state.isAuthenticated = false;
    },
  },
});

// Exporting the actions generated by createSlice
export const { login, logout } = rootReducer.actions;

// Default export the reducer
export default rootReducer.reducer;
